# Generated by Django 5.1 on 2024-08-21 02:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='list',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.list'),
            preserve_default=False,
        ),
    ]
