# Generated by Django 5.1 on 2024-08-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_list_task_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['updated_at']},
        ),
    ]
